version: "3.8"

services:
  mongo:
    container_name: mongo_container
    image: mongo:latest
    environment:
      - MONGO_DATABASE="amazon"
    ports:
      - 27018:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
     - mongo
    ports:
      - 5000:8081
